const SET_POLYGON_DATA = 'SET_POLYGON_DATA';
const SET_BOTTOM_DRAWER_DATA = 'SET_BOTTOM_DRAWER_DATA';

const TOGGLE_LEFT_DRAWER = 'TOGGLE_LEFT_DRAWER';
const TOGGLE_RIGHT_DRAWER = 'TOGGLE_RIGHT_DRAWER';
const TOGGLE_BOTTOM_DRAWER = 'TOGGLE_BOTTOM_DRAWER';

const FIND_MY_LOCATION_SELECT = 'FIND_MY_LOCATION_SELECT';
const FIND_MY_LOCATION_ERROR = 'FIND_MY_LOCATION_ERROR';
const FIND_MY_LOCATION_SUCCESS = 'FIND_MY_LOCATION_SUCCESS';
const FIND_MY_LOCATION_OUT_OF_BOUNDS = 'FIND_MY_LOCATION_OUT_OF_BOUNDS';

const SET_MAP = 'SET_MAP';

const SET_TAB_VALUE = 'SET_TAB_VALUE';

// TODO put this in a better place
const drawerWidth = 280;

export {
  SET_POLYGON_DATA,
  SET_BOTTOM_DRAWER_DATA,
  TOGGLE_LEFT_DRAWER,
  TOGGLE_RIGHT_DRAWER,
  TOGGLE_BOTTOM_DRAWER,
  FIND_MY_LOCATION_SELECT,
  FIND_MY_LOCATION_ERROR,
  FIND_MY_LOCATION_SUCCESS,
  FIND_MY_LOCATION_OUT_OF_BOUNDS,
  SET_TAB_VALUE,
  SET_MAP,
  drawerWidth
}
