const SET_POLYGON_DATA = 'SET_POLYGON_DATA';
const TOGGLE_LEFT_MENU = 'TOGGLE_LEFT_MENU';
const TOGGLE_RIGHT_MENU = 'TOGGLE_RIGHT_MENU';

export {
  SET_POLYGON_DATA,
  TOGGLE_LEFT_MENU,
  TOGGLE_RIGHT_MENU
}