const SET_POLYGON_DATA = 'SET_POLYGON_DATA';
const TOGGLE_LEFT_MENU = 'TOGGLE_LEFT_MENU';
const TOGGLE_RIGHT_MENU = 'TOGGLE_RIGHT_MENU';
const FIND_MY_LOCATION_SELECT = 'FIND_MY_LOCATION_SELECT';
const FIND_MY_LOCATION_ERROR = 'FIND_MY_LOCATION_ERROR';
const FIND_MY_LOCATION_SUCCESS = 'FIND_MY_LOCATION_SUCCESS';
const FIND_MY_LOCATION_OUT_OF_BOUNDS = 'FIND_MY_LOCATION_OUT_OF_BOUNDS';

export {
  SET_POLYGON_DATA,
  TOGGLE_LEFT_MENU,
  TOGGLE_RIGHT_MENU,
  FIND_MY_LOCATION_SELECT,
  FIND_MY_LOCATION_ERROR,
  FIND_MY_LOCATION_SUCCESS,
  FIND_MY_LOCATION_OUT_OF_BOUNDS
}
